# Aula 02

-   **Aula 2: Probabilidade Condicionada e Independência**
-   **Prof. Dr. Carlos Enrique Carrasco Gutierrez**
-   **E-mail: carlos.carrasco.gutierrez\@gmail.com**

## Definição 12 (Probabilidade condicional)

A probabilidade condicionada refere-se à probabilidade de um evento $(E_1)$ sabendo que ocorreu um outro evento $(E_2)$, e representa-se por $(P(E_1 | E_2 ))$, informalmente lida como "probabilidade condicional de $(E_1)$ dado $(E_2)$". É definido como:

$P(E_1 | E_2 ) = \frac{P(E_1 \cap E_2 )}{P( E_2)}$

**Observação**:

$P(E_1 | E_2 ) \neq P(E_1)$

Onde $(P( E_2 ) > 0)$. A partir desta definição podemos encontrar a probabilidade da interseção de dois eventos:

$P(E_1 \cap E_2 ) = P(E_1 | E_2 ) \times P( E_2)$

Ou também para o Evento 2:

$P(E_2 | E_1 ) = \frac{P(E_2 \cap E_1 )}{P( E_1)} = \frac{P(E_1 \cap E_2 )}{P( E_1)}$

\*Obs: $P(E_1 | E_2 ) \neq P(E_1)$

***Exemplo 1:***

Consideremos 250 alunos que cursam o terceiro período da UCB. Destes alunos, 100 são homens (H) e 150 mulheres (M); 110 cursam Física (F) e 140 cursam Economia (E) das quais têm 40 homens que estudam Física e 80 mulheres que estudam Economia. Existem 40 homens estudando física e 80 mulheres estudando economia. Um aluno é sorteado ao acaso. Pede-se:

a\) Qual é a probabilidade de que este cursando Economia dado que é mulher?

$P(E|M) = \frac{80}{150}$

b\) Qual é a probabilidade de que seja mulher e este cursando Economia?

$P(M \cap E) = \frac{80}{250}$

c\) Qual é a probabilidade de ser mulher?

$P(M) = \frac{150}{250}$

Podemos também encontrar a probabilidade condicional usando a definição de probabilidade condicional, definição 6, como:

$P(E|M) = \frac{P(E \cap M)}{P(M)} = \frac{\frac{80}{250}}{\frac{150}{250}}$

$P(E|M) = \frac{80}{150}$

*Exemplo 2:*

Seja $(P(A)=\frac{1}{3})$, $(P(B)=\frac{3}{4})$ e $(P(A \cup B)=\frac{11}{12})$. Calcule $P(A | B)$.

*Solução:*

Pela definição de probabilidade condicional:

$P(A | B)=\frac{P(A \cap B)}{P(B)} =\frac{P(A \cap B)}{\frac{3}{4}}$

Para encontrar a probabilidade condicionada devemos encontrar primeiramente $(P(A\cap B))$. Podemos encontrar isso da relação: $(P(A\cup B)=P(A)+P(B)-P(A\cap B))$.

$\frac{11}{12} = \frac{1}{3} + \frac{3}{4} - P(A\cap B)$

$P(A\cap B)=\frac{1}{6}$

Logo, em (1) temos:

$P(A | B)=\frac{\frac{1}{6}}{\frac{3}{4}}=\frac{2}{9}$

## Definição 13 (Independência):

Dois eventos A e B com probabilidades positivas são estatisticamente independentes se:

$P(A | B)=P(A)$

ou de forma equivalente:

$P(A\cap B)=P(A)P(B)$

\*Lembre da definição de probabilidade condicional. Se $(A)$ e $(B)$ são eventos independentes, então:\*

$P(A | B)=P(A\cap B)/P(B) =P(A)$

\*Logo:\*

$P(A\cap B)=P(A)P(B)$

\*Observação:\* $P(A| B)=P(A)$

## Teorema de Bayes:

Se $(A)$ e $(B)$ são dois eventos com probabilidades conhecidas, então:

$P(A|B) = \frac{P(B|A) \times P(A)}{P(B)}$

*Demonstração:*

Inicialmente, deve-se entender que $( (A\cap B)=(B\cap A) )$. Após, aplica-se a definição 12 de probabilidade condicional dada por

$P(E_1 | E_2 ) = P(E_1\cap E_2 )/(P( E_2)$.

Desta forma,

$P(A | B)= \frac{P(A\cap B)}{P(B)}$

Todavia, sabemos que $A \cap B = B \cap A$, então

$P(B|A)= \frac{P(B\cap A)}{P(A)}$

Quando aplicamos a regra vista anteriormente; $P(B\cap A)=P(A)\times P(B|A)$

Portanto, o Teorema de Bayes,

$P(A | B)= \frac{P(A\cap B)}{P(B)}=\frac{P(B\cap A)}{P(B)}=\frac{P(B|A) \times P(A)}{P(B)}$

## Teorema de Bayes estendido:

Sejam $(A_1, A_2,..., A_n)$ eventos que formam uma partição do espaço amostral. Seja $(B)$ um evento desse espaço. Então para cada $(j=1, 2, ... ,n)$:

$P(A_j|B)=\frac{P(B|A_j) \times P(A_j)}{P(B)}=\frac{P(B|A_j) \times P(A_j)}{\sum_{i=1}^n P(B|A_i) \times P(A_i) }$

**Demonstração:**

Aplicando o Teorema de Bayes em $P(A_j|B)$:

$P(A_j|B)=\frac{P(A_j \cap B)}{P(B)}=\frac{P(B|A_j) \times P(A_j)}{P(B)}$

Como os $(A_j)$'s constituem partição de $(\Omega)$ podemos escrever $(B)$ como:

$B=(A_1 \cap B)\cup(A_2\cap B) \cup...\cup (A_j\cap B)$

Aplicando o Axioma 3 de Kolmogorov (Definição 10):

$P(B)=P({A_1\cap B}\cup{A_2\cap B}\cup...\cup{A_j\cap B})=P({A_1\cap B})+P({A_2\cap B})+...+P({A_j\cap B})$

Lembre da definição de probabilidade condicional:

$P(B|A_j )=P(A_j\cap B)/(P(A_j))$

Usando a definição de probabilidade condicional $( P({A_j\cap B})=P(B|A_j )\times P(A_j) )$ podemos reescrever $P(B)$ da seguinte forma:

$P(B)=P(B|A_1) \times P(A_1 ) + P(B|A_2 ) \times P(A_2 ) +...+ P(B|A_n ) \times P(A_n )$ = $\sum_{i=1}^n P(B|A_i) \times P(A_i)$

Substituímos $P(B)$ pela expressão acima:

$P(A_j|B)= \frac{P(B|A_j) \times P(A_j)}{P(B)} = \frac{P(B|A_j) \times P(A_j)}{\sum\_{i=1}^n P(B|A_i) \times P(A_i)}$

**Exemplo:**

Considere uma partição como mostrado na figura abaixo $(A_1, A_2, A_3, A_4)$.

$Omega$

$P(A_1|B) = \frac{P(B\cap A_1)}{P(B)}= \frac{P(A_1)\times P(B|A_1)}{P(A_1)\times P(B|A_1)+P(A_2)\times P(B|A_2)+P(A_3)\times P(B|A_3)+P(A_4)\times P(B|A_4)}$

**Exercício (encontrando a fonte de um item com defeito):**

Um mesmo produto é fabricado por três tipos de máquinas $(A_1, A_2)$ e $(A_3)$. Algumas informações a seguir são conhecidas:

-   25% dos itens foram produzidos pela máquina $(A_1)$;

-   30% dos itens foram produzidos pela máquina $(A_2)$;

-   45% dos itens foram produzidos pela máquina $(A_3)$;

Além disso:

-   2% dos itens fabricados por $(A_1)$ têm defeito.

-   4% dos itens fabricados por $(A_2)$ têm defeito.

-   6% dos itens fabricados por $(A_3)$ têm defeito.

Um produto é selecionado aleatoriamente e é defeituoso. Qual é a probabilidade de que este produto tenha sido fabricado por $(A_3)$?

**Solução:**

Considere os eventos:

$A_i = {\text{o item foi fabricado pela máquina } A_i}, \quad i = 1,2,3$

$B = {\text{o item é defeituoso}}$

$P(A_1)=25\%$

$P(A_2)=30\%$

$P(A_3)=45\%$

$P(B|A_1 )=2\%$

$P(B|A_2 )=4\%$

$P(B|A_3 )=6\%$

$P(A_3|B)=?$

Considere uma partição como mostrado na figura abaixo $(A_1, A_2, A_3)$.

$\Omega$

FIGURA

Pede:

$P(A_3|B)=\frac{P(B|A_3 )P(A_3)}{P(B)}$

$P(B)=P({A_1\cap B}\cup{A_2\cap B}\cup{A_3\cap B})=P({A_1\cap B})+P({A_2\cap B})+P({A_3\cap B})$

$P(B)=P(B|A_1 )P(A_1 )+P(B|A_2 )P(A_2 )+P(B|A_3 )P(A_3)=\sum_{i=1}^3 P(B|A_i )P(A_i )$

$P(B)=(2\%)(25\%)+(4\%)(30\%)+(6\%)(45\%)$
